export const personalInfo = { name: 'Andy Zhang', location: 'Waterloo, Ontario', headline: 'Curious by default. Builder by choice.', intro: "I'm a Computer Science student at the University of Waterloo. I build software across cloud infrastructure, spatial computing, developer tools, and applied machine learning.", aside: 'Away from the keyboard, you’ll find me turning a speedcube, thinking through a poker hand, or settling in for a board game.' };
export const contact = { email: 'andy.jy.zhang@gmail.com', github: 'https://github.com/andyjyzhang', linkedin: 'https://www.linkedin.com/in/andyzhang12/', resume: '/AndyZhangResume.pdf' };
export const experience = [
  { company: 'Statistics Canada', role: 'Software Engineering Intern', date: 'May — Aug 2026', stack: 'Python · Shiny · DuckDB · Azure · Kubernetes', detail: 'Built containerized data applications for survey and census workflows used by over 100 employees. Standardized Azure Blob Storage across five applications and automated releases with GitLab CI and Helm.', result: '6.9× faster XML-to-Parquet conversion, saving roughly 20 hours per large run.' },
  { company: 'Nokia', role: 'Software Engineering Intern', date: 'Jul — Aug 2024', stack: 'Python · Locust · Kubernetes · Grafana · Prometheus', detail: 'Built repeatable performance tests for Network Services Platform workflows, with scalable load testing, real-time metrics collection, and automated reports.', result: '75% reduction in analysis runtime.' },
];
export const projects = [
  { title: 'Reminiscence', category: 'Spatial computing', description: 'Phone video becomes an explorable VR memory. A reconstruction pipeline connects video frames, COLMAP, Gaussian splatting, and Unity OpenXR.', stack: 'PyTorch / Unity / FastAPI / Modal', links: [{ label: 'Visit project', url: 'https://reminiscence-two.vercel.app/' }, { label: 'Source code', url: 'https://github.com/andyjyzhang/reminiscence' }] },
  { title: 'AlphaHex', category: 'Game AI', description: 'A self-play Catan engine combining Monte Carlo tree search, board heuristics, and long-term resource strategy. Reached a top-500 online rank.', stack: 'PyTorch / MCTS / React', links: [{ label: 'Visit project', url: 'https://alphahex.vercel.app/' }] },
  { title: 'Photo Verification', category: 'Authenticity', description: 'Photo authenticity records anchored on Solana and matched with vector search.', stack: 'Rust / Solana / MongoDB', links: [] },
  { title: 'Memo Lab', category: 'Cubing tools', description: 'Exact blindfold-cubing memo practice with legal-solution validation.', stack: 'TypeScript / Cube state', links: [{ label: 'Visit project', url: 'https://blind-memo-lab.andy-jy-zhang.chatgpt.site' }, { label: 'Source code', url: 'https://github.com/andyjyzhang/3bld-helper' }] },
  { title: 'Range Visualizer', category: 'Data visualization', description: 'Maps poker frequencies onto every preflop hand combination, with offline access.', stack: 'React / PWA', links: [{ label: 'Source code', url: 'https://github.com/andyjyzhang/range-visualizer' }] },
  { title: 'Lawly', category: 'Document retrieval', description: 'Reads legal documents with OCR, retrieves relevant evidence, and explains it in context through a searchable document memory.', stack: 'Flask / Tesseract / Pinecone / RAG', links: [{ label: 'Source code', url: 'https://github.com/andyjyzhang/lawly' }] },
];
export const education = { institution: 'University of Waterloo', degree: 'Computer Science', date: '2023 — 2028', award: 'National Math Scholarship', awardDetail: '$15,000 scholarship awarded to 15 students.', courses: 'CS145 · CS146 · CS136L' };
export const hobbies = [ { title: 'Cubing', detail: 'Speedcubes, patterns, and the satisfaction of a good solve. I also built Memo Lab for blindfold-cubing practice.', icon: '▦' }, { title: 'Board games', detail: 'A table full of friends, a hexagonal island, and a plan that probably won’t survive the next turn. Catan is a favourite.', icon: '⬡' }, { title: 'Video games', detail: 'Another way to explore, experiment, and enjoy a challenge. This little world is a nod to that side of me.', icon: '⌘' } ];
export const poker = { title: 'Learning the game, one hand at a time.', intro: 'Poker is a hobby I’m actively working to improve at. The interesting part is the decision: what did I know, what did I miss, and what would I do differently?', topics: ['Study strategy', 'Review hands', 'Build better habits'], closing: 'This lounge is a place for that ongoing journey. No trophy wall needed.' };
